# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanjye', '0009_paymentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
